### ISSUE TITLE
ID e Token de Webhook a vista no Source!

### ISSUE THREAD

**Issue by TiaGoiNsaNy** [BONEE4/Fumiko#1]
## :computer: Token está a solta!

:thinking: Você deixou o **Token** e **ID** de **2 Webhook** no arquivo principal de sua aplicação, coloque eles dentro de uma variável local!

### :rainbow_flag: BONEE Gay! Não esperava isso de você!

**Comment by BONEE4** [comment]
Webhooks já foram deletados juntamente com o bot 😔
