### ISSUE TITLE
Token do Top.gg Está a Vista!

### ISSUE THREAD

**Issue by TiaGoiNsaNy** [BONEE4/Fumiko#2]
## :trackball: Novamente mais um Token está a vista!

:-1: Remova o **Token** do **Top.gg** no sua Source! Vai que alguém né... Use ele para outras coisas...

## :rainbow_flag: BONEE Gay! Não cometa esse erro novamente!

**Comment by BONEE4** [comment]
Eu já tinha regenerado antes de deixar open 😏😏😏😳
