### ISSUE TITLE
Quantos Tokens eu vou Encontrar no seu Projeto?

### ISSUE THREAD

**Issue by TiaGoiNsaNy** [BONEE4/Fumiko#3]
## :1st_place_medal: Você ganhou a Medalha do Usuário mais descuidado!

:monkey: Que macaquinho danadinho, você deixou agora o **Token** de sua aplicação dentro do arquivo de configurações `config.js`! Nem preciso dizer oque fazer...

## :rainbow_flag: BONEE meu Amor! Tenha mais cuidado!

**Comment by Lucaas1** [comment]
LAKSDOJFIHAUYUKLKKKKKKKKK
